FROM ubuntu:16.04

RUN apt-get update && apt-get install -y gawk grep python3 python3-pip python-dev automake make vim git bzip2 unzip wget python-pip cscope

RUN pip3 install AWSIoTPythonSDK 
RUN pip3 install python-dateutil

RUN useradd wwc
RUN mkdir /github
RUN chown wwc /github
USER wwc
WORKDIR /github
RUN git clone https://github.com/aws/aws-iot-device-sdk-python.git

VOLUME ["/main"]
VOLUME ["/certs"]
WORKDIR /
ENTRYPOINT ["python3", "/main/wwc_controller.py"]

