#ifndef TOPICS_INCLUDED
#define TOPICS_INCLUDED

#define WWC_ "wwc"
#define SLASH_ "/"
#define CONTROL_SUBTOPIC "control"
#define STATUS_SUBTOPIC "status"
#define PING_SUBTOPIC "ping"
#define SUBSCRIBTIONS_SUBTOPIC "$aws/events/subscriptions/subscribed"

#define SHADOW_TOPIC_PREFIX "$aws/things/" CONFIG_AWS_CLIENT_ID "/shadow"

#define SHADOW_TOPIC_GET SHADOW_TOPIC_PREFIX "/get"
#define SHADOW_TOPIC_GET_ACCEPTED SHADOW_TOPIC_PREFIX "/get/accepted"
#define SHADOW_TOPIC_UPDATE_DELTA "update/delta"

#define CONTROL_TOPIC WWC_ SLASH_ CONFIG_AWS_CLIENT_ID SLASH_ CONTROL_SUBTOPIC
#define STATUS_TOPIC WWC_ SLASH_ CONFIG_AWS_CLIENT_ID SLASH_ STATUS_SUBTOPIC
#define TIMESTAMP_TOPIC SUBSCRIBTIONS_SUBTOPIC SLASH_ CONFIG_AWS_CLIENT_ID
#define PING_TOPIC WWC_ SLASH_ CONFIG_AWS_CLIENT_ID SLASH_ PING_SUBTOPIC

#endif
